[build]
publish = "public"
command = "gutenberg build"

[build.environment]
GUTENBERG_VERSION = "0.4.2"

# The magic for deploying previews of branches
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.
[context.deploy-preview]
command = "gutenberg build --base-url $DEPLOY_PRIME_URL"
